#Build functions in this script

#dummy function to test source() call in scripts --> just run hw() 
hw <- function(){print("Hello World")} 


# Temporal Moments --------------------------------------------------------

# param full_tib: tibble without flags or unknown values
format_input <- function(full_tib) {
  full_tib %>% # changing everything to the correct date/time format
    mutate(h = as.numeric(format(datetime, format = "%H")),
           m = as.numeric(format(datetime, format = "%M"))/60,
           h_elapsed = h+m, 
           day_text = format(datetime, format = "%Y-%m-%d")) %>%
    mutate(day = as.POSIXct(day_text)) %>% #convert datetime text to POSIXct object
    select(-day_text) #remove day_text column
}


master_format_input <- function(full_tib) {
  full_tib %>% # changing everything to the correct date/time format
    mutate(datetime = as.POSIXct(datetime)) %>% 
    mutate(h = as.numeric(format(datetime, format = "%H")),
           m = as.numeric(format(datetime, format = "%M"))/60,
           h_elapsed = h+m, 
           day_text = format(datetime, format = "%Y-%m-%d")) %>%
    mutate(day = as.POSIXct(day_text)) %>% #convert datetime text to POSIXct object
    select(-day_text) #remove day_text column
}

# param formatted_tib: tibble generated from tib_formatting
# param n: specifies highest temporal moment (currently deprecated)
calculate_cumulative_moment_by_day <- function(formatted_tib, n) {
  formatted_tib %>% 
    group_by(day) %>%
    
    # calls all moments 
    
    mutate(zeroth = cumtrapz(as.numeric(h_elapsed),
                                   as.numeric(sap_vel)*as.numeric(h_elapsed)^0)) %>%
    
    mutate(first = cumtrapz(as.numeric(h_elapsed),
                             as.numeric(sap_vel)*as.numeric(h_elapsed)^1)) %>%
    
    mutate(second = cumtrapz(as.numeric(h_elapsed),
                             as.numeric(sap_vel)*as.numeric(h_elapsed)^2)) %>%
    
    mutate(third = cumtrapz(as.numeric(h_elapsed),
                             as.numeric(sap_vel)*as.numeric(h_elapsed)^3)) %>%
    
    mutate(fourth = cumtrapz(as.numeric(h_elapsed),
                             as.numeric(sap_vel)*as.numeric(h_elapsed)^4))
}

# param cumulative_moment_by_day: tibble generated by cumulative_moment_by_day
calculate_daily_cumulative <- function(cumulative_moment_by_day) {
  cumulative_moment_by_day %>%
    group_by(day) %>%
    mutate(entries = n()) %>% # keeps track of day
    mutate(completeness = if_else(entries == 96, TRUE, FALSE)) %>%
    slice(n()) %>% # using slice(1,n()) would give first and last
    select(-datetime, -h, -m, -h_elapsed, -sap_vel)
}

# param cumulated_sap_tibble_all: tibble of Zeroth, First, Second, Third, Fourth moments
calculate_all_measures <- function(cumulated_sap_tibble_all) {
  
  output_tibble <- cumulated_sap_tibble_all %>%
    
  mutate(centroid = first/zeroth) %>% # Centroid
    
  mutate(variance = (second/zeroth) 
         - ((first/zeroth)^2)) %>% # Variance
    
  mutate(skewness = (third/zeroth) 
         - (3*variance*(first/zeroth))
         -((first/zeroth)^3))%>% # Skewness
    
  mutate(kurtosis = (fourth/zeroth) 
         - (4*skewness*(first/zeroth))
         - (6*variance*((first/zeroth)^2))
         - ((first/zeroth)^4)) %>% # Kurtosis
  
  select(-c(first, second, third, fourth)) %>%
  
  rename(sap_flux = zeroth)
  
  return(output_tibble)
}

master_temporal_moments <- function(sap_vel_tibble, plot, probe, placement, save_pdf = TRUE) {

  # creating tibble of all moments at each time step
  formatted_tibble <- master_format_input(sap_vel_tibble)
    
    # FIXME add conditionals to specify highest order
  cumulated_sap_tibble_all <- calculate_cumulative_moment_by_day(formatted_tibble , 0)
  
  # creating plot of all zero moment instances
  cumulated_sap_tibble_all %>%
    ggplot(aes(x = h_elapsed, y = zeroth, group = day, colour = day)) +
    geom_line() +
    theme_bw()
  
  # creating daily cumulative totals for all measures for all measures
  daily_cumulative_all <- calculate_daily_cumulative(cumulated_sap_tibble_all)
  
  # creating plot of cumulative zeroth moment
  daily_cumulative_all %>%
    ungroup() %>%
    ggplot(aes(x = day, y = zeroth)) +
    geom_point(aes(color = completeness)) + 
    theme_bw()
  
  # all statistical measures derived from cumulative totals
  all_measures <- calculate_all_measures(daily_cumulative_all)
  
  # Plot Statistical Measures --------------------------------------------
  
  # pivot longer 
  long_all_measures <- all_measures %>%
    pivot_longer(!c(day, index, entries, completeness), names_to = "measure", values_to = "value")
  
  # plot faceted long measures
  long_all_measures %>%
    ungroup() %>% 
    ggplot(aes(x = day, y = value, group = 1)) + # plotting in groups of 1
    geom_line(aes(color = completeness)) + # basic lineplot
    theme_bw() + 
    labs(title = "All Statistical Measures") + 
    facet_wrap(~ measure, scales = "free") #scale freely
  
  if (save_pdf == TRUE) {
    pdf_name = paste(plot, probe, placement, "Statistical_Measures.pdf", sep = "_")
    ggsave(path = "../data/temporal_moments", pdf_name)  
  }
  
  return(all_measures)
}

harmon_master_temporal_moments <- function(sap_vel_tibble) {
  
  # creating tibble of all moments at each time step
  formatted_tibble <- master_format_input(sap_vel_tibble)
  
  # FIXME add conditionals to specify highest order
  cumulated_sap_tibble_all <- calculate_cumulative_moment_by_day(formatted_tibble , 0)
  
  # creating plot of all zero moment instances
  cumulated_sap_tibble_all %>%
    ggplot(aes(x = h_elapsed, y = zeroth, group = day, colour = day)) +
    geom_line() +
    theme_bw()
  
  # creating daily cumulative totals for all measures for all measures
  daily_cumulative_all <- calculate_daily_cumulative(cumulated_sap_tibble_all)
  
  # creating plot of cumulative zeroth moment
  daily_cumulative_all %>%
    ungroup() %>%
    ggplot(aes(x = day, y = zeroth)) +
    geom_point(aes(color = completeness)) + 
    theme_bw()
  
  # all statistical measures derived from cumulative totals
  all_measures <- calculate_all_measures(daily_cumulative_all)
  
  # Plot Statistical Measures --------------------------------------------
  
  # pivot longer 
  long_all_measures <- all_measures %>%
    pivot_longer(!c(day, index, entries, completeness, placement), names_to = "measure", values_to = "value")
  
  # plot faceted long measures
  long_all_measures %>%
    ungroup() %>% 
    ggplot(aes(x = day, y = value, group = 1)) + # plotting in groups of 1
    geom_line(aes(color = placement)) + # basic lineplot
    theme_bw() + 
    labs(title = "All Statistical Measures") + 
    facet_wrap(~ measure, scales = "free") #scale freely
  
  pdf_name = paste("Harmon_data_Statistical_Measures.pdf", sep = "_")
  
  ggsave(path = "../data/temporal_moments", pdf_name)  
  
  return(all_measures)
}
